name: ci-client

on:
  push:
    paths:
      - 'src/client/**'
      - '!src/client/.devcontainer/**'
      - '!src/client/.vscode/**'
      - '!src/client/.gitignore'
  pull_request:
    paths:
      - 'src/client/**'
      - '!src/client/.devcontainer/**'
      - '!src/client/.vscode/**'
      - '!src/client/.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Install dependencies
        working-directory: src/client
        run: go get
      - name: Test
        working-directory: src/client
        run: go test
      - name: Build
        working-directory: src/client
        run: |
          mkdir build
          go build -o build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: client-${{ matrix.os }}
          path: src/client/build/*
