name: ci-server

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/app/TicketStore.Server*/**'
      - '!src/app/.devcontainer/**'
      - '!src/app/.vscode/**'
      - '!src/app/.gitignore'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/app/TicketStore.Server*/**'
      - '!src/app/.devcontainer/**'
      - '!src/app/.vscode/**'
      - '!src/app/.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet v3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        working-directory: src/app/TicketStore.Server.App
        run: dotnet restore
      - name: Build
        working-directory: src/app/TicketStore.Server.App
        run: dotnet build --no-restore --configuration Release 
      - name: Test
        working-directory: src/app/TicketStore.Server.App
        run: dotnet test --no-restore
      - name: Publish
        working-directory: src/app/TicketStore.Server.App
        run: dotnet publish --no-restore -o build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: server-${{ matrix.os }}
          path: src/app/TicketStore.Server.App/build/*
