name: CI

on:
  push:
    paths:
      - 'src/documentation/**'
    paths-ignore:
      - 'src/documentation/.devcontainer/**'
      - 'src/documentation/.vscode/**'
      - 'src/documentation/.gitignore'
  pull_request:

jobs:

  build-documentation:
    name: Build documentation pdf file
    runs-on: ubuntu-18.04
    container:
      image: skyfrk/udhbwvst:5.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display versions of build tools
        run: |
          latexmk -v
          lualatex --version
          java -jar $PLANTUML_JAR -version
      - name: Build
        run: |
          latexmk \
          -pdf \
          -file-line-error \
          -interaction=nonstopmode \
          -cd \
          -pdflatex=lualatex \
          -synctex=1 \
          -shell-escape \
          src/documentation/root.tex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: src/documentation/root.pdf

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy to GitHub Releases
    needs: [ build ]
    runs-on: ubuntu-18.04
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Prepare
        run: |
          mkdir staging
          mv artifacts/documentation/root.pdf "staging/WWI17B_Seminararbeit_ABE1_Gruppe_B4-${GITHUB_REF##*/}.pdf"
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
