name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-documentation:
    name: Build documentation pdf file
    runs-on: ubuntu-18.04
    container:
      image: skyfrk/udhbwvst:5.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display versions of build tools
        run: |
          latexmk -v
          lualatex --version
          java -jar $PLANTUML_JAR -version
      - name: Build
        run: |
          latexmk \
          -pdf \
          -file-line-error \
          -interaction=nonstopmode \
          -cd \
          -pdflatex=lualatex \
          -synctex=1 \
          -shell-escape \
          src/documentation/root.tex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: src/documentation/root.pdf
  build-app:
    name: Build app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet v3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        working-directory: src/app
        run: dotnet restore
      - name: Build
        working-directory: src/app
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: src/app
        run: dotnet test --no-restore
      - name: Publish
        working-directory: src/app
        run: dotnet publish TicketStore.sln  --no-restore --self-contained -o build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: src/app/build/*
  deploy:
    name: Deploy to GitHub Releases
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ build-documentation, build-app ]
    runs-on: ubuntu-18.04
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Prepare
        run: |
          mkdir staging
          mv artifacts/documentation/root.pdf "staging/WWI17B_Seminararbeit_ABE1_Gruppe_B4-${GITHUB_REF##*/}.pdf"
          mv artifacts/app** staging
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
